name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: python .github/check_examples.py
      - run: echo "VITE_GIT_SHA=$(git rev-parse --short HEAD)" >> app/.env
      - run: cd extra && npm install
      - run: cd app && npm install && ./node_modules/.bin/tsc && ./node_modules/.bin/vite build --base=/protomaps-themes/
      - run: cd examples && mkdir ../app/dist/examples && cp *.html ../app/dist/examples/
      - name: build_app
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
          force_orphan: true
